In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_excel("Acoustic_Extinguisher_Fire_Dataset.xlsx")

In [3]:
df.head()

SIZE      FUEL  DISTANCE  DESIBEL  AIRFLOW  FREQUENCY  STATUS
0     1  gasoline        10       96      0.0         75       0
1     1  gasoline        10       96      0.0         72       1
2     1  gasoline        10       96      2.6         70       1
3     1  gasoline        10       96      3.2         68       1
4     1  gasoline        10      109      4.5         67       1

In [4]:
df["FUEL"].unique()

array(['gasoline', 'thinner', 'kerosene', 'lpg'], dtype=object)

In [5]:
df.duplicated().sum()

0

In [6]:
df.isna().sum()

SIZE         0
FUEL         0
DISTANCE     0
DESIBEL      0
AIRFLOW      0
FREQUENCY    0
STATUS       0
dtype: int64

In [7]:
df.dtypes

SIZE           int64
FUEL          object
DISTANCE       int64
DESIBEL        int64
AIRFLOW      float64
FREQUENCY      int64
STATUS         int64
dtype: object

In [8]:
df.columns

Index(['SIZE', 'FUEL', 'DISTANCE', 'DESIBEL', 'AIRFLOW', 'FREQUENCY',
       'STATUS'],
      dtype='object')

In [9]:
df = df[['FUEL', 'SIZE', 'DISTANCE', 'DESIBEL', 'AIRFLOW', 'FREQUENCY','STATUS']]

In [10]:
df.head()

FUEL  SIZE  DISTANCE  DESIBEL  AIRFLOW  FREQUENCY  STATUS
0  gasoline     1        10       96      0.0         75       0
1  gasoline     1        10       96      0.0         72       1
2  gasoline     1        10       96      2.6         70       1
3  gasoline     1        10       96      3.2         68       1
4  gasoline     1        10      109      4.5         67       1

In [11]:
x = df.drop("STATUS",axis=1)
y = df["STATUS"]

In [12]:
x

FUEL  SIZE  DISTANCE  DESIBEL  AIRFLOW  FREQUENCY
0      gasoline     1        10       96      0.0         75
1      gasoline     1        10       96      0.0         72
2      gasoline     1        10       96      2.6         70
3      gasoline     1        10       96      3.2         68
4      gasoline     1        10      109      4.5         67
...         ...   ...       ...      ...      ...        ...
17437       lpg     7       190       86      2.2          5
17438       lpg     7       190       84      2.0          4
17439       lpg     7       190       80      1.5          3
17440       lpg     7       190       76      0.4          2
17441       lpg     7       190       72      0.0          1

[17442 rows x 6 columns]

In [13]:
y

0        0
1        1
2        1
3        1
4        1
        ..
17437    0
17438    0
17439    0
17440    0
17441    0
Name: STATUS, Length: 17442, dtype: int64

In [14]:
from sklearn.preprocessing import OneHotEncoder

In [15]:
one = OneHotEncoder(sparse=False,handle_unknown='ignore')

In [16]:
x_dup =pd.DataFrame(one.fit_transform(x.iloc[:,0:1]),columns=one.get_feature_names_out())
x_dup.reset_index(inplace = True)

In [17]:
x.drop(columns=["FUEL"],inplace=True)

In [18]:
x.reset_index(inplace = True)

In [19]:
x = pd.concat([x,x_dup],axis=1)

In [20]:
x.reset_index(inplace = True)
x

level_0  index  SIZE  DISTANCE  DESIBEL  AIRFLOW  FREQUENCY  index  \
0            0      0     1        10       96      0.0         75      0   
1            1      1     1        10       96      0.0         72      1   
2            2      2     1        10       96      2.6         70      2   
3            3      3     1        10       96      3.2         68      3   
4            4      4     1        10      109      4.5         67      4   
...        ...    ...   ...       ...      ...      ...        ...    ...   
17437    17437  17437     7       190       86      2.2          5  17437   
17438    17438  17438     7       190       84      2.0          4  17438   
17439    17439  17439     7       190       80      1.5          3  17439   
17440    17440  17440     7       190       76      0.4          2  17440   
17441    17441  17441     7       190       72      0.0          1  17441   

       FUEL_gasoline  FUEL_kerosene  FUEL_lpg  FUEL_thinner  
0                1.0            0.0       0.0           0.0  
1                1.0            0.0       0.0           0.0  
2                1.0            0.0       0.0           0.0  
3                1.0            0.0       0.0           0.0  
4                1.0            0.0       0.0           0.0  
...              ...            ...       ...           ...  
17437            0.0            0.0       1.0           0.0  
17438            0.0            0.0       1.0           0.0  
17439            0.0            0.0       1.0           0.0  
17440            0.0            0.0       1.0           0.0  
17441            0.0            0.0       1.0           0.0  

[17442 rows x 12 columns]

In [21]:
x = x.drop(columns=["level_0","index"], axis=1)
x

SIZE  DISTANCE  DESIBEL  AIRFLOW  FREQUENCY  FUEL_gasoline  \
0         1        10       96      0.0         75            1.0   
1         1        10       96      0.0         72            1.0   
2         1        10       96      2.6         70            1.0   
3         1        10       96      3.2         68            1.0   
4         1        10      109      4.5         67            1.0   
...     ...       ...      ...      ...        ...            ...   
17437     7       190       86      2.2          5            0.0   
17438     7       190       84      2.0          4            0.0   
17439     7       190       80      1.5          3            0.0   
17440     7       190       76      0.4          2            0.0   
17441     7       190       72      0.0          1            0.0   

       FUEL_kerosene  FUEL_lpg  FUEL_thinner  
0                0.0       0.0           0.0  
1                0.0       0.0           0.0  
2                0.0       0.0           0.0  
3                0.0       0.0           0.0  
4                0.0       0.0           0.0  
...              ...       ...           ...  
17437            0.0       1.0           0.0  
17438            0.0       1.0           0.0  
17439            0.0       1.0           0.0  
17440            0.0       1.0           0.0  
17441            0.0       1.0           0.0  

[17442 rows x 9 columns]

In [22]:
import joblib

In [23]:
joblib.dump(one,"OneHotee.joblib")

['OneHotee.joblib']

In [24]:
from sklearn.tree import DecisionTreeClassifier

In [25]:
classifier = DecisionTreeClassifier()

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=32)

In [28]:
classifier.fit(x_train,y_train)

DecisionTreeClassifier()

In [29]:
classifier.score(x_train,y_train)

1.0

In [30]:
classifier.score(x_test,y_test)

0.9638830498757882

In [31]:
pre = classifier.predict(x_test)

In [32]:
pre

array([0, 1, 0, ..., 0, 0, 1], dtype=int64)

In [33]:
from sklearn.metrics import classification_report
print(classification_report(y_test,pre))

              precision    recall  f1-score   support

           0       0.96      0.97      0.96      2678
           1       0.97      0.96      0.96      2555

    accuracy                           0.96      5233
   macro avg       0.96      0.96      0.96      5233
weighted avg       0.96      0.96      0.96      5233



In [34]:
joblib.dump(classifier,"classifier.pkl")

['classifier.pkl']

In [35]:
check=df.copy()

In [36]:
check=check.head(2)
check

FUEL  SIZE  DISTANCE  DESIBEL  AIRFLOW  FREQUENCY  STATUS
0  gasoline     1        10       96      0.0         75       0
1  gasoline     1        10       96      0.0         72       1

In [37]:
check.drop("STATUS",axis=1,inplace=True)

In [38]:
check

FUEL  SIZE  DISTANCE  DESIBEL  AIRFLOW  FREQUENCY
0  gasoline     1        10       96      0.0         75
1  gasoline     1        10       96      0.0         72

In [39]:
one_hot = joblib.load("OneHotee.joblib")
one_hot

OneHotEncoder(handle_unknown='ignore', sparse=False)

In [40]:
l=one_hot.transform(check.iloc[:,0:1])
l

array([[1., 0., 0., 0.],
       [1., 0., 0., 0.]])

In [41]:
c = one_hot.get_feature_names_out()

In [42]:
c

array(['FUEL_gasoline', 'FUEL_kerosene', 'FUEL_lpg', 'FUEL_thinner'],
      dtype=object)

In [43]:
t = pd.DataFrame(l,columns=c)
t

FUEL_gasoline  FUEL_kerosene  FUEL_lpg  FUEL_thinner
0            1.0            0.0       0.0           0.0
1            1.0            0.0       0.0           0.0

In [44]:
check

FUEL  SIZE  DISTANCE  DESIBEL  AIRFLOW  FREQUENCY
0  gasoline     1        10       96      0.0         75
1  gasoline     1        10       96      0.0         72

In [45]:
l2 = check.iloc[:,1:]

In [46]:
l2

SIZE  DISTANCE  DESIBEL  AIRFLOW  FREQUENCY
0     1        10       96      0.0         75
1     1        10       96      0.0         72

In [47]:
final = pd.concat([l2,t],axis=1)
final

SIZE  DISTANCE  DESIBEL  AIRFLOW  FREQUENCY  FUEL_gasoline  FUEL_kerosene  \
0     1        10       96      0.0         75            1.0            0.0   
1     1        10       96      0.0         72            1.0            0.0   

   FUEL_lpg  FUEL_thinner  
0       0.0           0.0  
1       0.0           0.0

In [48]:
final_model = joblib.load("classifier.pkl")
final_model

DecisionTreeClassifier()

In [49]:
final_model.predict(final) 

array([0, 1], dtype=int64)